# # Even Fibonacci numbers
# # Problem 2
# # Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2,
# # the first 10 terms will be:
# # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# # By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the
# # even-valued terms.

current_term = 2
previous_term = 1

fibo_array = [1, 2]

while current_term < 3524578:
    previous_term, current_term = current_term, previous_term + current_term
    fibo_array.append(current_term)

print(fibo_array)

fibo_sum = []

for i in fibo_array:
    if i % 2 == 0:
        fibo_sum.append(i)

print(fibo_sum)
print(sum(fibo_sum))
